export const SIZE = {
    FONT_SIZE_SMALL: 14,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_LARGE: 20,
    PADDING_SMALL: 18,
    PADDING_MEDIUM: 20,
    PADDING_LARGE: 30,
    MARGIN_SMALL: 10,
    MARGIN_MEDIUM: 20,
    MARGIN_LARGE: 30,
    BORDER_RADIUS_SMALL: 5,
    BORDER_RADIUS_MEDIUM: 10,
    BORDER_RADIUS_LARGE: 20,
  };
  
  